### PR TITLE
Tag link functionality

### PR DESCRIPTION
**Pull request by PxlH00t**
Adding functionality to tags so when they are clicked they pull up the explore component with a search value.

Explore and NavBar components were using redundant code to search for projects so I extracted the searchProject method from the Explore component and created a new Explore Service so that future Components can use the Service without creating more redundant code.

### CODE REVIEW

**Comment by cengique** [comment]
@TrippBarker ok, this is cool. But I don't see the "Tag" option in the pull down of the Explore page. Can you make it official in there so that when the filter activates it actually populates the text box with the tag as well?

**Comment by PxlH00t** [comment]
@cengique Do you mean the dropdown with Project and Profile? There is no Tag option there because the tags are used for searching for Projects, so I just have it searching for Projects with the related tag. I did not notice it was not populating the textbox, I will get that working today!

**Comment by cengique** [comment]
> @cengique Do you mean the dropdown with Project and Profile? There is no Tag option there because the tags are used for searching for Projects, so I just have it searching for Projects with the related tag. I did not notice it was not populating the textbox, I will get that working today!

Yes, that's what I meant! But you're right, it's still searching for projects, so it can stay there. Will you define an "advanced search" syntax then (like on GitHub)?

**Comment by PxlH00t** [comment]
@cengique I certainly can try my hand at making some advance search syntax, that sounds like it will be fun to work out.

**Review by cengique — APPROVED** [review]
Works, although it would have been nice to update the search box with the terms

**Pull request merged**
